### PR TITLE
Add plex/emby instructions and link from README

### PR DESCRIPTION
**Pull request by eiddor**
- From #26 
- Created new `docs/` directory for extra documentation
- Add instructions for both Plex and Emby
- link from `README.md`

### CODE REVIEW

**Comment by wouterdebie** [comment]
This is so awesome! I'd like @Croc360 to have  a look as well, but this looks great. One thing though is that the links to these docs are somewhat hidden in the README. Should we think about restructuring that doc a bit?

**Comment by eiddor** [comment]
I agree - I fiddled with a couple of different places, but could never find the right place between "hidden" and making it look like an annoying spam email.

Maybe I could put them in a quick start section after the install section?

**Comment by Croq360** [comment]
I took a look at the Plex instructions, and they look good to me.  They appear to be exactly the same steps I follow to set it up.

My next step is going to be to dockerize locast2tuner (on my Windows 10 box), and since I'm using XTeVe to do some channel remapping, get that in there as well.  That way, if my machine reboots, everything should automatically just start back up without me needing to do anything.

**Comment by eiddor** [comment]
Thanks, @Croq360!  Docker is magical.

@wouterdebie I rebased everything into one commit.

**Pull request merged**
